### PR TITLE
update: added Cex for $SEI

### PR DESCRIPTION
**Pull request by nidz-the-fact**
## Describe the changes to the documentation
update: added Cex for $SEI

### CODE REVIEW

**Review by cordt-sei — COMMENTED** [review]
Looks OK but I'm unsure if this section is staying here.

**Comment by nidz-the-fact** [comment]
There seems to be one in this section as well. I don't know which update I should focus on. @cordt-sei 
https://www.docs.sei.io/dev-ecosystem-providers/centralized-exchanges


image

**Comment by nidz-the-fact** [comment]
**I think this option should be added and updated for users.**

**Review by ghost — APPROVED** [review]
Should be ok to add while the section is available. Disclaimer is also present

**Review by cordt-sei — APPROVED** [review]
fair enough

**Pull request merged**
