### PR TITLE
Add Gas Fee Estimation

### PR DESCRIPTION
**Pull request by laurencedelisle**
Adding the gas fee estimation API to the Sei documentation.

## What is the purpose of the change?

Adding new content to Sei documentation to help developers get started quickly.

## Describe the changes to the documentation

Added the new Sei gas fee estimation API developed by Blocknative. This will help developers setup their infrastructure quickly and efficiently.

## Notes

### CODE REVIEW

**Review by cordt-sei — COMMENTED** [review]
I think we should wait until we have dynamic gas pricing to merge this.

**Comment by laurencedelisle** [comment]
Hey @cordt-sei ! Thanks for the comment. Chatting with the Sei team we are working with it might be best to get the API out there sooner so that when things change devs know exactly where to go versus having to wait and scramble.

**Comment by cordt-sei** [comment]
Hey @laurencedelisle would you be able to add some more detailed docs for this? Just enough so that someone who is already experienced with it can get the basic info they need to set this up without going to an external page.

**Comment by alexander-sei** [comment]
Superceeded by a new PR

**Pull request closed without merging**
