### PR TITLE
feat: Cookbook Onboard (AI Assistant & Playground) integration

### PR DESCRIPTION
**Pull request by ClockRide**
## What is the purpose of the change?

Introduces Cookbook Onboard, featuring an AI Assistant and a Playground. A more detailed description is provided below.

## Describe the changes to the documentation

- Added the `@cookbookdev/docsbot` dependency and an `AskCookbook` component to wrap it.
- Included the `<AskCookbook>` component in `_app.tsx`.

## Preview
Preview link: https://sei-docs-cookbook.vercel.app/

## Ask Cookbook AI Assistant
Cookbook's Ask Cookbook AI assistant and co-pilot is trained on all existing Sei resources (source code, docs website, etc.) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about building on Sei, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity coding co-pilot.

Ask Cookbook AI can also access context from thousands of data sources indexed by Cookbook.dev in addition to Sei-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.

image
  

## Cookbook Onboard Playground
The Cookbook Onboard Playground embeds a Solidity IDE with smart contract templates displayed alongside the Ask Cookbook AI Assistant.

Developers can search for and deploy Cookbook’s entire smart contract library from your technical documentation.

Features:
- Deploy smart contracts or entire protocols to Sei without leaving the docs
- Acts as a free, no-code or low-code token and NFT launchpad
- Save source code as a Foundry, Hardhat, or Scaffold project or export it to Remix or Chain IDE in one click

image

### CODE REVIEW

**Comment by cordt-sei** [comment]
Hey @ClockRide can you check the conflicts here please

**Comment by ClockRide** [comment]
> Hey @ClockRide can you check the conflicts here please

Should be all good now!

**Review by besated — APPROVED** [review]

**Comment by besated** [comment]
Looks like there's some conflicts - can you resolve @ClockRide?

**Comment by ClockRide** [comment]
@besated, resolved conflicts

**Review by besated — APPROVED** [review]

**Pull request merged**
