### PR TITLE
[feat] adds envio as supported data indexing framework & data infr provider

### PR DESCRIPTION
**Pull request by SvenMuller95**
## What is the purpose of the change?

adds envio as supported data indexing framework & data infr provider to sei evm

## Describe the changes to the documentation

adds a paragraph in line with existing format for envio as supported data indexing framework & data infr provider to sei evm

### CODE REVIEW

**Comment by cordt-sei** [comment]
Please add to the bottom of the list to maintain chronological order.

**Comment by SvenMuller95** [comment]
@cordt-sei I've changed the ordering to maintain ordering, thanks!

**Comment by SvenMuller95** [comment]
Hey @cordt-sei , i can't seem to see the conflicts. But I've done as asked. Can you take a look please and let me know

**Review by cordt-sei — APPROVED** [review]

**Comment by SvenMuller95** [comment]
hey @cordt-sei , is this all okay?

**Comment by cordt-sei** [comment]
I'm not sure what the conflicts are here. Try opening it in an IDE maybe?

**Pull request closed without merging**
