### PR TITLE
Add Gem Wallet to list of wallets

### PR DESCRIPTION
**Pull request by gemcoder21**
## What is the purpose of the change?

Adding [Gem Wallet](https://gemwallet.com) as supported list of wallets for Sei. 

Page for Sei Wallet: https://gemwallet.com/sei-wallet/

Gem Wallet is fully open source:

1) Core: https://github.com/gemwalletcom/core
2) iOS App: https://github.com/gemwalletcom/gem-ios
3) Android: https://github.com/gemwalletcom/gem-android

Screenshot 2024-06-10 at 18 50 03

### CODE REVIEW

**Review by cordt-sei — COMMENTED** [review]
I tested this wallet app, it's fast and it works, very simple to use. The features are not very many, but there is walletconnect, and staking available with all validators. 

I don't see an issue with adding it here.

**Review by codebycarson — APPROVED** [review]

**Comment by cordt-sei** [comment]
Hey @gemcoder21 can you check into the walletconnect config for Sei? It seems like no apps want to to actually connect to the wallet app.

They all seem to try to connect fine:
image


But then it goes back to this:
image


And nothing is actually connected. 
I Tried several:
 - `https://dragonswap.app` 
 - `https://jellyverse.org`

**Comment by gemcoder21** [comment]
@cordt-sei we currently only support SEI as cosmos based chain (transfer + staking), looking into adding support for EVM compatibility.

**Comment by gemcoder21** [comment]
@cordt-sei https://chainlist.org/chain/1329 is this correct configuration to support Sei EVM?

@cordt-sei can you ping me on telegram [@gemcoder ](https://t.me/gemcoder) to finish evm support.

**Pull request merged**
